version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    command: ["/app/wait-for-it.sh", "mongodb:27017", "--timeout=30", "--", "node", "/app/src/server.js"]
  ml-service:
    build: ./ml-service
    ports:
      - "6000:6000"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=totallyspies
      - ME_CONFIG_BASICAUTH_PASSWORD=totallyspies
    depends_on:
      - mongodb
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  mongodb_data:
  jenkins_home:

