FROM node:18
WORKDIR /app

# Copy the wait-for-it script and start script
COPY wait-for-it.sh start-script.sh /app/

# Set permissions

RUN chmod +x /app/wait-for-it.sh /app/start-script.sh


# install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the files
COPY . /app/

# Use the start script as the entrypoint
CMD ["/app/start-script.sh"]
