# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Install required Python packages
RUN pip install --no-cache-dir requests py7zr google-transit pyspark

# Copy the current directory contents into the container at /app
COPY . /app

# Run your script when the container launches
CMD ["python", "./your_script.py"]
